#nullable enable
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace Grid.Generator;

internal static class DataGridRenderer
{
    public static string Render(DataGridModel dataGrid, WorldGridModel world, ImmutableArray<DataGridModel?> allDataGrids)
    {
        int cellSizeInTiles = dataGrid.CellSizePixels / world.TileSize;
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using Core;");

        // Add using for WorldTile if in different namespace
        if (dataGrid.Namespace != world.Namespace)
        {
            sb.AppendLine($"using {world.Namespace};");
        }

        sb.AppendLine();
        sb.AppendLine($"namespace {dataGrid.Namespace};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// {dataGrid.TypeName} coordinate. Each cell is {dataGrid.CellSizePixels}x{dataGrid.CellSizePixels} pixels ({cellSizeInTiles}x{cellSizeInTiles} tiles).");
        sb.AppendLine($"/// Grid is {dataGrid.Dimensions}x{dataGrid.Dimensions} cells.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public readonly partial struct {dataGrid.TypeName} : IEquatable<{dataGrid.TypeName}>");
        sb.AppendLine("{");

        // Constants
        sb.AppendLine($"    public const int CellSizePixels = {dataGrid.CellSizePixels};");
        sb.AppendLine($"    public const int GridWidth = {dataGrid.Dimensions};");
        sb.AppendLine($"    public const int GridHeight = {dataGrid.Dimensions};");
        sb.AppendLine($"    public const int TotalCells = {dataGrid.Dimensions * dataGrid.Dimensions};");
        sb.AppendLine($"    public const int CellSizeInTiles = {cellSizeInTiles};");
        sb.AppendLine();

        // Pre-computed Fixed64 constants
        sb.AppendLine("    public static readonly Fixed64 CellSizeFixed = Fixed64.FromInt(CellSizePixels);");
        sb.AppendLine("    public static readonly Fixed64 HalfCellSizeFixed = Fixed64.FromInt(CellSizePixels / 2);");
        sb.AppendLine();

        // Fields
        sb.AppendLine("    public readonly int X;");
        sb.AppendLine("    public readonly int Y;");
        sb.AppendLine();
        sb.AppendLine($"    public static readonly {dataGrid.TypeName} Zero = new(0, 0);");
        sb.AppendLine();

        // Constructor
        sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"    public {dataGrid.TypeName}(int x, int y)");
        sb.AppendLine("    {");
        sb.AppendLine("        X = x;");
        sb.AppendLine("        Y = y;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Factory Methods
        sb.AppendLine("    // === Factory Methods ===");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Convert pixel position to cell coordinate.</summary>");
        sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"    public static {dataGrid.TypeName} FromPixel(Fixed64Vec2 pixelPos)");
        sb.AppendLine("    {");
        sb.AppendLine("        int cellX = (pixelPos.X / CellSizeFixed).ToInt();");
        sb.AppendLine("        int cellY = (pixelPos.Y / CellSizeFixed).ToInt();");
        sb.AppendLine($"        return new {dataGrid.TypeName}(cellX, cellY).Clamped();");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Convert pixel position to cell coordinate (unclamped).</summary>");
        sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"    public static {dataGrid.TypeName} FromPixelUnclamped(Fixed64Vec2 pixelPos)");
        sb.AppendLine("    {");
        sb.AppendLine("        int cellX = (pixelPos.X / CellSizeFixed).ToInt();");
        sb.AppendLine("        int cellY = (pixelPos.Y / CellSizeFixed).ToInt();");
        sb.AppendLine($"        return new {dataGrid.TypeName}(cellX, cellY);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Convert tile coordinate to cell coordinate.</summary>");
        sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"    public static {dataGrid.TypeName} FromTile(WorldTile tile)");
        sb.AppendLine("    {");
        sb.AppendLine($"        return new {dataGrid.TypeName}(tile.X / CellSizeInTiles, tile.Y / CellSizeInTiles);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Convert tile coordinates to cell coordinate.</summary>");
        sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"    public static {dataGrid.TypeName} FromTile(int tileX, int tileY)");
        sb.AppendLine("    {");
        sb.AppendLine($"        return new {dataGrid.TypeName}(tileX / CellSizeInTiles, tileY / CellSizeInTiles);");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Conversion Methods
        sb.AppendLine("    // === Conversion Methods ===");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Get pixel position of cell center.</summary>");
        sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("    public Fixed64Vec2 ToPixelCenter()");
        sb.AppendLine("    {");
        sb.AppendLine("        return new Fixed64Vec2(");
        sb.AppendLine("            Fixed64.FromInt(X * CellSizePixels) + HalfCellSizeFixed,");
        sb.AppendLine("            Fixed64.FromInt(Y * CellSizePixels) + HalfCellSizeFixed");
        sb.AppendLine("        );");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Get the center tile of this cell.</summary>");
        sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("    public WorldTile ToTileCenter()");
        sb.AppendLine("    {");
        sb.AppendLine("        int tileX = X * CellSizeInTiles + CellSizeInTiles / 2;");
        sb.AppendLine("        int tileY = Y * CellSizeInTiles + CellSizeInTiles / 2;");
        sb.AppendLine("        return new WorldTile(tileX, tileY);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Get the top-left tile of this cell.</summary>");
        sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("    public WorldTile ToTileTopLeft()");
        sb.AppendLine("    {");
        sb.AppendLine("        return new WorldTile(X * CellSizeInTiles, Y * CellSizeInTiles);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Convert to 1D array index (row-major).</summary>");
        sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("    public int ToIndex()");
        sb.AppendLine("    {");
        sb.AppendLine("        return Y * GridWidth + X;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Create from 1D array index (row-major).</summary>");
        sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"    public static {dataGrid.TypeName} FromIndex(int index)");
        sb.AppendLine("    {");
        sb.AppendLine($"        return new {dataGrid.TypeName}(index % GridWidth, index / GridWidth);");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Bounds Checking
        sb.AppendLine("    // === Bounds Checking ===");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Check if cell is within grid bounds.</summary>");
        sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("    public bool IsInBounds()");
        sb.AppendLine("    {");
        sb.AppendLine("        return X >= 0 && X < GridWidth && Y >= 0 && Y < GridHeight;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Clamp to grid bounds.</summary>");
        sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"    public {dataGrid.TypeName} Clamped()");
        sb.AppendLine("    {");
        sb.AppendLine($"        return new {dataGrid.TypeName}(");
        sb.AppendLine("            Math.Clamp(X, 0, GridWidth - 1),");
        sb.AppendLine("            Math.Clamp(Y, 0, GridHeight - 1)");
        sb.AppendLine("        );");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Cross-grid conversions
        var otherGrids = allDataGrids.Where(g => g != null && g.TypeName != dataGrid.TypeName).ToList();
        if (otherGrids.Count > 0)
        {
            sb.AppendLine("    // === Cross-Grid Conversions ===");
            sb.AppendLine();
            foreach (var other in otherGrids)
            {
                if (other == null) continue;

                // Calculate ratio
                if (dataGrid.CellSizePixels >= other.CellSizePixels)
                {
                    // This cell is larger or equal - maps to top-left of multiple smaller cells
                    int ratio = dataGrid.CellSizePixels / other.CellSizePixels;
                    sb.AppendLine($"    /// <summary>Convert to {other.TypeName} (top-left of {ratio}x{ratio} {other.TypeName}s).</summary>");
                    sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
                    sb.AppendLine($"    public {other.TypeName} To{other.TypeName}()");
                    sb.AppendLine("    {");
                    sb.AppendLine($"        return new {other.TypeName}(X * {ratio}, Y * {ratio});");
                    sb.AppendLine("    }");
                    sb.AppendLine();
                }
                else
                {
                    // This cell is smaller - multiple of these fit in one of the other
                    int ratio = other.CellSizePixels / dataGrid.CellSizePixels;
                    sb.AppendLine($"    /// <summary>Convert to {other.TypeName} (containing cell, {ratio}x{ratio} {dataGrid.TypeName}s per {other.TypeName}).</summary>");
                    sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
                    sb.AppendLine($"    public {other.TypeName} To{other.TypeName}()");
                    sb.AppendLine("    {");
                    sb.AppendLine($"        return new {other.TypeName}(X / {ratio}, Y / {ratio});");
                    sb.AppendLine("    }");
                    sb.AppendLine();
                }
            }
        }

        // Operators
        sb.AppendLine("    // === Operators ===");
        sb.AppendLine();
        sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"    public static {dataGrid.TypeName} operator +({dataGrid.TypeName} a, {dataGrid.TypeName} b)");
        sb.AppendLine("        => new(a.X + b.X, a.Y + b.Y);");
        sb.AppendLine();
        sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"    public static {dataGrid.TypeName} operator -({dataGrid.TypeName} a, {dataGrid.TypeName} b)");
        sb.AppendLine("        => new(a.X - b.X, a.Y - b.Y);");
        sb.AppendLine();
        sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"    public static bool operator ==({dataGrid.TypeName} a, {dataGrid.TypeName} b)");
        sb.AppendLine("        => a.X == b.X && a.Y == b.Y;");
        sb.AppendLine();
        sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"    public static bool operator !=({dataGrid.TypeName} a, {dataGrid.TypeName} b)");
        sb.AppendLine("        => a.X != b.X || a.Y != b.Y;");
        sb.AppendLine();

        // IEquatable
        sb.AppendLine("    // === IEquatable ===");
        sb.AppendLine();
        sb.AppendLine($"    public bool Equals({dataGrid.TypeName} other) => X == other.X && Y == other.Y;");
        sb.AppendLine($"    public override bool Equals(object? obj) => obj is {dataGrid.TypeName} other && Equals(other);");
        sb.AppendLine("    public override int GetHashCode() => HashCode.Combine(X, Y);");
        sb.AppendLine($"    public override string ToString() => $\"{dataGrid.TypeName}({{X}}, {{Y}})\";");

        sb.AppendLine("}");

        return sb.ToString();
    }
}
