using Catrillion.Config;
using Grid;

// Assembly-level world grid definition - references GameConfig as the source of truth
[assembly: WorldGrid(
    TileSize = GameConfig.Map.TileSize,
    WidthTiles = GameConfig.Map.WidthTiles,
    HeightTiles = GameConfig.Map.HeightTiles,
    Namespace = "Catrillion.Simulation.Grids")]

namespace Catrillion.Simulation.Grids;

/// <summary>
/// Noise grid: 32x32 cells, each 256px (8x8 tiles).
/// Used for zombie attraction via noise generated by buildings and units.
/// </summary>
[DataGrid(
    CellSizePixels = GameConfig.NoiseGrid.CellSizePixels,
    Dimensions = GameConfig.NoiseGrid.Dimensions)]
public readonly partial struct NoiseCell { }

/// <summary>
/// Threat grid: 64x64 cells, each 128px (4x4 tiles).
/// Used for zombie state transitions and pathfinding priority.
/// </summary>
[DataGrid(
    CellSizePixels = GameConfig.ThreatGrid.CellSizePixels,
    Dimensions = GameConfig.ThreatGrid.Dimensions)]
public readonly partial struct ThreatCell { }

/// <summary>
/// Power grid: 256x256 cells, each 32px (1:1 with tiles).
/// Used for building placement validation - tiles within range of powered broadcasters.
/// </summary>
[DataGrid(
    CellSizePixels = GameConfig.PowerGrid.CellSizePixels,
    Dimensions = GameConfig.PowerGrid.Dimensions)]
public readonly partial struct PowerCell { }
