using System;
using Microsoft.CodeAnalysis;

namespace DerpLib.Ecs.Generator;

[Generator]
public sealed class DerpEcsDomainGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValueProvider<string?> domain = context.AnalyzerConfigOptionsProvider.Select(
            static (provider, _) =>
            {
                if (provider.GlobalOptions.TryGetValue("build_property.DerpEcsDomain", out string? value))
                {
                    return value;
                }

                return null;
            });

        context.RegisterSourceOutput(domain, static (spc, domainValue) =>
        {
            if (domainValue == null)
            {
                return;
            }

            string normalized = domainValue.Trim();
            if (!string.Equals(normalized, "Simulation", StringComparison.Ordinal) &&
                !string.Equals(normalized, "View", StringComparison.Ordinal))
            {
                spc.ReportDiagnostic(Diagnostic.Create(Diagnostics.InvalidDomain, Location.None, normalized));
                return;
            }

            spc.AddSource(
                "DerpEcsDomain.g.cs",
                $"// <auto-generated/>\n#nullable enable\nnamespace DerpLib.Ecs;\n\ninternal static class DerpEcsDomain\n{{\n    public const string Value = \"{normalized}\";\n}}\n");
        });
    }
}

