using System.Text;

namespace GameDocDatabase.Generator;

/// <summary>
/// Generates JSON DTO and binary serialization code for each schema struct.
/// </summary>
internal static class BinarySerializerRenderer
{
    public static string Render(TableSchemaModel model)
    {
        var sb = new StringBuilder(4096);

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Runtime.InteropServices;");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine("using Core;");
        sb.AppendLine("using FixedMath;");
        sb.AppendLine("using GameDocDatabase;");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace};");
        sb.AppendLine();

        // JSON DTO class (Color32Dto is defined in Core.Color32.cs)
        RenderJsonDto(sb, model);
        sb.AppendLine();

        // Extension methods for serialization
        RenderExtensions(sb, model);

        return sb.ToString();
    }

    private static void RenderJsonDto(StringBuilder sb, TableSchemaModel model)
    {
        sb.AppendLine($"/// <summary>JSON-compatible DTO for {model.TypeName}.</summary>");
        sb.AppendLine($"public sealed class {model.TypeName}JsonDto");
        sb.AppendLine("{");

        foreach (var field in model.Fields)
        {
            var jsonType = GetJsonType(field.TypeName, field.Name);
            var defaultValue = jsonType == "string" ? " = \"\";" : "";
            sb.AppendLine($"    public {jsonType} {field.Name} {{ get; set; }}{defaultValue}");
        }

        sb.AppendLine("}");
    }

    private static void RenderExtensions(StringBuilder sb, TableSchemaModel model)
    {
        sb.AppendLine($"/// <summary>Serialization extensions for {model.TypeName}.</summary>");
        sb.AppendLine($"public static class {model.TypeName}Serialization");
        sb.AppendLine("{");

        // FromJsonDto - converts DTO to schema struct
        sb.AppendLine($"    /// <summary>Converts JSON DTO to schema struct.</summary>");
        sb.AppendLine($"    public static {model.TypeName} FromJsonDto({model.TypeName}JsonDto dto)");
        sb.AppendLine("    {");
        sb.AppendLine($"        return new {model.TypeName}");
        sb.AppendLine("        {");

        foreach (var field in model.Fields)
        {
            var conversion = GetFromJsonConversion(field.TypeName, field.Name, $"dto.{field.Name}");
            sb.AppendLine($"            {field.Name} = {conversion},");
        }

        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine();

        // ParseJsonArray - parses JSON array to struct array
        sb.AppendLine($"    /// <summary>Parses JSON array to schema struct array.</summary>");
        sb.AppendLine($"    public static {model.TypeName}[] ParseJsonArray(string json)");
        sb.AppendLine("    {");
        sb.AppendLine("        var options = new JsonSerializerOptions { PropertyNameCaseInsensitive = true };");
        sb.AppendLine($"        var dtos = JsonSerializer.Deserialize<{model.TypeName}JsonDto[]>(json, options)");
        sb.AppendLine($"            ?? throw new InvalidOperationException(\"Failed to parse JSON for {model.TypeName}\");");
        sb.AppendLine();
        sb.AppendLine($"        var result = new {model.TypeName}[dtos.Length];");
        sb.AppendLine("        for (int i = 0; i < dtos.Length; i++)");
        sb.AppendLine("        {");
        sb.AppendLine("            result[i] = FromJsonDto(dtos[i]);");
        sb.AppendLine("        }");
        sb.AppendLine("        return result;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // GetRecordSize - returns size of struct in bytes
        sb.AppendLine($"    /// <summary>Size of {model.TypeName} in bytes.</summary>");
        sb.AppendLine($"    public static int RecordSize => Marshal.SizeOf<{model.TypeName}>();");

        sb.AppendLine("}");
    }

    /// <summary>
    /// Gets the JSON-compatible type for a field type.
    /// </summary>
    private static string GetJsonType(string typeName, string fieldName)
    {
        // GameDataId fields named "Name" are strings in JSON (human-readable names)
        // but the actual value comes from the Id field
        if ((typeName == "GameDocDatabase.GameDataId" || typeName == "GameDataId") && fieldName == "Name")
        {
            return "string";
        }

        return typeName switch
        {
            "Core.Fixed64" or "Fixed64" or "FixedMath.Fixed64" => "double",
            "Core.Fixed32" or "Fixed32" or "FixedMath.Fixed32" => "double",
            "Core.StringHandle" or "StringHandle" => "string",  // StringHandle uses string in JSON
            "Core.Color32" or "Color32" => "Color32Dto",  // Color32 needs a DTO for deserialization
            "GameDocDatabase.GameDataId" or "GameDataId" => "int",
            "int" => "int",
            "bool" => "bool",
            "string" => "string",
            _ => typeName // fallback
        };
    }

    /// <summary>
    /// Gets the conversion expression from JSON type to schema type.
    /// </summary>
    private static string GetFromJsonConversion(string typeName, string fieldName, string dtoField)
    {
        // GameDataId fields named "Name" use the record's Id for the GameDataId value
        if ((typeName == "GameDocDatabase.GameDataId" || typeName == "GameDataId") && fieldName == "Name")
        {
            return "new GameDataId(dto.Id)";
        }

        return typeName switch
        {
            "Core.Fixed64" or "Fixed64" or "FixedMath.Fixed64" => $"Fixed64.FromDouble({dtoField})",
            "Core.Fixed32" or "Fixed32" or "FixedMath.Fixed32" => $"Fixed32.FromDouble({dtoField})",
            "Core.StringHandle" or "StringHandle" => dtoField,  // Implicit conversion from string to StringHandle
            "Core.Color32" or "Color32" => $"new Color32({dtoField}.R, {dtoField}.G, {dtoField}.B, {dtoField}.A)",
            "GameDocDatabase.GameDataId" or "GameDataId" => $"new GameDataId({dtoField})",
            _ => dtoField // int, bool, string - direct assignment
        };
    }
}
