using System.Collections.Generic;
using System.Text;

namespace GameDocDatabase.Generator;

/// <summary>
/// Generates GameDataBinaryBuilder that orchestrates building all tables to .bin.
/// </summary>
internal static class BinaryBuilderRenderer
{
    public static string Render(List<TableSchemaModel> tables, string targetNamespace)
    {
        var sb = new StringBuilder(8192);

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.IO;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Runtime.InteropServices;");
        sb.AppendLine("using Core;");
        sb.AppendLine("using FixedMath;");
        sb.AppendLine("using GameDocDatabase.Runtime;");
        sb.AppendLine();
        sb.AppendLine($"namespace {targetNamespace};");
        sb.AppendLine();

        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Builds GameData.bin from JSON source files.");
        sb.AppendLine("/// Auto-generated - do not modify.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class GameDataBinaryBuilder");
        sb.AppendLine("{");

        // Build method
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Builds binary data file from JSON source directory.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"jsonDir\">Directory containing JSON data files.</param>");
        sb.AppendLine("    /// <param name=\"outputPath\">Output path for the .bin file.</param>");
        sb.AppendLine("    public static void Build(string jsonDir, string outputPath)");
        sb.AppendLine("    {");
        sb.AppendLine("        var builder = new BinaryBuilder();");
        sb.AppendLine();

        foreach (var table in tables)
        {
            sb.AppendLine($"        // Process {table.TableName}");
            sb.AppendLine($"        {{");
            sb.AppendLine($"            var jsonPath = Path.Combine(jsonDir, \"{table.TableName}.json\");");
            sb.AppendLine($"            if (File.Exists(jsonPath))");
            sb.AppendLine($"            {{");
            sb.AppendLine($"                var json = File.ReadAllText(jsonPath);");
            sb.AppendLine($"                var records = {table.TypeName}Serialization.ParseJsonArray(json);");
            sb.AppendLine($"                builder.AddTable(\"{table.TableName}\", records, r => r.{table.PrimaryKey?.Name ?? "Id"});");
            sb.AppendLine($"                Console.WriteLine($\"  {table.TableName}: {{records.Length}} records\");");
            sb.AppendLine($"            }}");
            sb.AppendLine($"        }}");
            sb.AppendLine();
        }

        sb.AppendLine("        // Collect string registry entries from all parsed data");
        sb.AppendLine("        var stringEntries = StringRegistry.Instance.GetAllEntries()");
        sb.AppendLine("            .Select(e => new StringRegistryEntry(e.Id, e.Value))");
        sb.AppendLine("            .ToList();");
        sb.AppendLine("        builder.SetStringRegistry(stringEntries);");
        sb.AppendLine("        Console.WriteLine($\"  StringRegistry: {stringEntries.Count} entries\");");
        sb.AppendLine();
        sb.AppendLine("        builder.WriteTo(outputPath);");
        sb.AppendLine("        Console.WriteLine($\"Binary written to: {outputPath}\");");
        sb.AppendLine("    }");

        sb.AppendLine("}");

        return sb.ToString();
    }
}
