using System.Text;

namespace GameDocDatabase.Generator;

internal static class TableRenderer
{
    public static string Render(TableSchemaModel model)
    {
        var sb = new StringBuilder(8192);

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using System.Runtime.InteropServices;");
        sb.AppendLine("using GameDocDatabase;");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace};");
        sb.AppendLine();

        sb.AppendLine($"public sealed class {model.TypeName}Table");
        sb.AppendLine("{");

        // Fields
        sb.AppendLine("    private readonly {0}[] _records;", model.TypeName);
        sb.AppendLine("    private readonly int _count;");

        // Slot arrays for O(1) lookup
        if (model.PrimaryKey != null)
        {
            sb.AppendLine($"    private readonly int[] _slotBy{model.PrimaryKey.Name};");
            sb.AppendLine($"    private readonly int _maxPrimaryKey;");
        }

        foreach (var sk in model.SecondaryKeys)
        {
            if (!sk.IsNonUnique)
            {
                sb.AppendLine($"    private readonly int[] _slotBy{sk.Field.Name};");
            }
            else
            {
                sb.AppendLine($"    private readonly (int Start, int Count)[] _rangesBy{sk.Field.Name};");
            }
        }

        sb.AppendLine();

        // Constructor
        sb.AppendLine($"    public {model.TypeName}Table({model.TypeName}[] records)");
        sb.AppendLine("    {");
        sb.AppendLine("        _records = records;");
        sb.AppendLine("        _count = records.Length;");

        if (model.PrimaryKey != null)
        {
            var pk = model.PrimaryKey;
            sb.AppendLine();
            sb.AppendLine("        // Build primary key slot array for O(1) lookup");
            sb.AppendLine($"        int maxId = 0;");
            sb.AppendLine($"        for (int i = 0; i < _count; i++)");
            sb.AppendLine($"        {{");
            sb.AppendLine($"            int id = GetPrimaryKey(records[i]);");
            sb.AppendLine($"            if (id > maxId) maxId = id;");
            sb.AppendLine($"        }}");
            sb.AppendLine($"        _maxPrimaryKey = maxId;");
            sb.AppendLine($"        _slotBy{pk.Name} = new int[maxId + 1];");
            sb.AppendLine($"        Array.Fill(_slotBy{pk.Name}, -1);");
            sb.AppendLine($"        for (int i = 0; i < _count; i++)");
            sb.AppendLine($"        {{");
            sb.AppendLine($"            int id = GetPrimaryKey(records[i]);");
            sb.AppendLine($"            _slotBy{pk.Name}[id] = i;");
            sb.AppendLine($"        }}");
        }

        // Build secondary key indexes
        foreach (var sk in model.SecondaryKeys)
        {
            sb.AppendLine();
            if (!sk.IsNonUnique)
            {
                // Unique secondary key - build slot array
                sb.AppendLine($"        // Build secondary key slot array for {sk.Field.Name}");
                sb.AppendLine($"        int max{sk.Field.Name} = 0;");
                sb.AppendLine($"        for (int i = 0; i < _count; i++)");
                sb.AppendLine($"        {{");
                sb.AppendLine($"            int key = (int)records[i].{sk.Field.Name};");
                sb.AppendLine($"            if (key > max{sk.Field.Name}) max{sk.Field.Name} = key;");
                sb.AppendLine($"        }}");
                sb.AppendLine($"        _slotBy{sk.Field.Name} = new int[max{sk.Field.Name} + 1];");
                sb.AppendLine($"        Array.Fill(_slotBy{sk.Field.Name}, -1);");
                sb.AppendLine($"        for (int i = 0; i < _count; i++)");
                sb.AppendLine($"        {{");
                sb.AppendLine($"            int key = (int)records[i].{sk.Field.Name};");
                sb.AppendLine($"            _slotBy{sk.Field.Name}[key] = i;");
                sb.AppendLine($"        }}");
            }
            else
            {
                // Non-unique secondary key - build range arrays
                sb.AppendLine($"        // Build secondary key range array for {sk.Field.Name} (non-unique)");
                sb.AppendLine($"        // First, sort records by {sk.Field.Name} and count groups");
                sb.AppendLine($"        Array.Sort(records, (a, b) => ((int)a.{sk.Field.Name}).CompareTo((int)b.{sk.Field.Name}));");
                sb.AppendLine($"        int max{sk.Field.Name} = _count > 0 ? (int)records[_count - 1].{sk.Field.Name} : 0;");
                sb.AppendLine($"        _rangesBy{sk.Field.Name} = new (int, int)[max{sk.Field.Name} + 1];");
                sb.AppendLine($"        if (_count > 0)");
                sb.AppendLine($"        {{");
                sb.AppendLine($"            int currentKey = (int)records[0].{sk.Field.Name};");
                sb.AppendLine($"            int start = 0;");
                sb.AppendLine($"            for (int i = 1; i <= _count; i++)");
                sb.AppendLine($"            {{");
                sb.AppendLine($"                int key = i < _count ? (int)records[i].{sk.Field.Name} : -1;");
                sb.AppendLine($"                if (key != currentKey)");
                sb.AppendLine($"                {{");
                sb.AppendLine($"                    _rangesBy{sk.Field.Name}[currentKey] = (start, i - start);");
                sb.AppendLine($"                    if (i < _count)");
                sb.AppendLine($"                    {{");
                sb.AppendLine($"                        currentKey = key;");
                sb.AppendLine($"                        start = i;");
                sb.AppendLine($"                    }}");
                sb.AppendLine($"                }}");
                sb.AppendLine($"            }}");
                sb.AppendLine($"        }}");
            }
        }

        sb.AppendLine("    }");
        sb.AppendLine();

        // Count property
        sb.AppendLine("    public int Count");
        sb.AppendLine("    {");
        sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("        get => _count;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // All records
        sb.AppendLine($"    public ReadOnlySpan<{model.TypeName}> All");
        sb.AppendLine("    {");
        sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("        get => _records.AsSpan(0, _count);");
        sb.AppendLine("    }");
        sb.AppendLine();

        // GetPrimaryKey helper
        if (model.PrimaryKey != null)
        {
            var pk = model.PrimaryKey;
            sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine($"    private static int GetPrimaryKey(in {model.TypeName} record)");
            sb.AppendLine("    {");
            if (pk.TypeName == "int" || pk.TypeName == "System.Int32")
            {
                sb.AppendLine($"        return record.{pk.Name};");
            }
            else if (pk.TypeName.Contains("GameDataId"))
            {
                sb.AppendLine($"        return record.{pk.Name}.Value;");
            }
            else
            {
                sb.AppendLine($"        return (int)record.{pk.Name};");
            }
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        // Primary key lookup - O(1) via slot array
        if (model.PrimaryKey != null)
        {
            var pk = model.PrimaryKey;
            var pkParamName = ToCamelCase(pk.Name);

            // Always generate int overload
            RenderFindByPrimaryKey(sb, model, pk, "int", pkParamName);
            RenderTryFindByPrimaryKey(sb, model, pk, "int", pkParamName);

            // Generate GameDataId overload
            RenderFindByPrimaryKey(sb, model, pk, "GameDataId", pkParamName);
            RenderTryFindByPrimaryKey(sb, model, pk, "GameDataId", pkParamName);

            // Generate enum overload if convention-based enum type exists
            // The enum is generated by RegistryRenderer in the same namespace
            var enumType = GetConventionalEnumType(model.TypeName);
            if (enumType != null)
            {
                RenderFindByPrimaryKey(sb, model, pk, enumType, pkParamName);
                RenderTryFindByPrimaryKey(sb, model, pk, enumType, pkParamName);
            }

            // Unsafe version that skips bounds checking for maximum performance
            sb.AppendLine($"    /// <summary>O(1) lookup by {pk.Name} - UNSAFE, no bounds checking. Use when id is guaranteed valid.</summary>");
            sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine($"    public ref readonly {model.TypeName} FindBy{pk.Name}Unsafe(int {pkParamName})");
            sb.AppendLine("    {");
            sb.AppendLine($"        ref int slotRef = ref MemoryMarshal.GetArrayDataReference(_slotBy{pk.Name});");
            sb.AppendLine($"        int slot = Unsafe.Add(ref slotRef, {pkParamName});");
            sb.AppendLine($"        ref {model.TypeName} recordRef = ref MemoryMarshal.GetArrayDataReference(_records);");
            sb.AppendLine($"        return ref Unsafe.Add(ref recordRef, slot);");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        // Binary search lookup for comparison (not using slot array)
        if (model.PrimaryKey != null)
        {
            var pk = model.PrimaryKey;
            var pkType = pk.TypeName == "int" || pk.TypeName == "System.Int32" ? "int" : pk.TypeName;

            sb.AppendLine($"    /// <summary>O(log n) lookup by {pk.Name} using binary search (for benchmark comparison).</summary>");
            sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine($"    public ref readonly {model.TypeName} FindBy{pk.Name}BinarySearch({pkType} {ToCamelCase(pk.Name)})");
            sb.AppendLine("    {");
            if (pkType == "int")
            {
                sb.AppendLine($"        int targetId = {ToCamelCase(pk.Name)};");
            }
            else if (pk.TypeName.Contains("GameDataId"))
            {
                sb.AppendLine($"        int targetId = {ToCamelCase(pk.Name)}.Value;");
            }
            else
            {
                sb.AppendLine($"        int targetId = (int){ToCamelCase(pk.Name)};");
            }
            sb.AppendLine("        int lo = 0;");
            sb.AppendLine("        int hi = _count - 1;");
            sb.AppendLine("        while (lo <= hi)");
            sb.AppendLine("        {");
            sb.AppendLine("            int mid = lo + ((hi - lo) >> 1);");
            sb.AppendLine("            int midId = GetPrimaryKey(_records[mid]);");
            sb.AppendLine("            if (midId == targetId)");
            sb.AppendLine("                return ref _records[mid];");
            sb.AppendLine("            if (midId < targetId)");
            sb.AppendLine("                lo = mid + 1;");
            sb.AppendLine("            else");
            sb.AppendLine("                hi = mid - 1;");
            sb.AppendLine("        }");
            sb.AppendLine($"        ThrowKeyNotFound(\"{pk.Name}\", targetId);");
            sb.AppendLine("        return ref _records[0]; // Unreachable");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        // GetAtIndex for direct access
        sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"    public ref readonly {model.TypeName} GetAtIndex(int index) => ref _records[index];");
        sb.AppendLine();

        // Secondary key lookups
        foreach (var sk in model.SecondaryKeys)
        {
            var fieldType = sk.Field.TypeName == "int" || sk.Field.TypeName == "System.Int32" ? "int" : sk.Field.TypeName;
            var paramName = ToCamelCase(sk.Field.Name);

            if (!sk.IsNonUnique)
            {
                // Unique secondary key - O(1) lookup
                sb.AppendLine($"    /// <summary>O(1) lookup by {sk.Field.Name} using slot array.</summary>");
                sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
                sb.AppendLine($"    public ref readonly {model.TypeName} FindBy{sk.Field.Name}({fieldType} {paramName})");
                sb.AppendLine("    {");
                sb.AppendLine($"        int keyValue = (int){paramName};");
                sb.AppendLine($"        if ((uint)keyValue >= (uint)_slotBy{sk.Field.Name}.Length)");
                sb.AppendLine($"            ThrowKeyNotFound(\"{sk.Field.Name}\", keyValue);");
                sb.AppendLine($"        int slot = _slotBy{sk.Field.Name}[keyValue];");
                sb.AppendLine("        if (slot < 0)");
                sb.AppendLine($"            ThrowKeyNotFound(\"{sk.Field.Name}\", keyValue);");
                sb.AppendLine("        return ref _records[slot];");
                sb.AppendLine("    }");
                sb.AppendLine();
            }
            else
            {
                // Non-unique secondary key - returns RangeView
                sb.AppendLine($"    /// <summary>O(1) range lookup by {sk.Field.Name}. Returns zero-allocation view of matching records.</summary>");
                sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
                sb.AppendLine($"    public RangeView<{model.TypeName}> FindBy{sk.Field.Name}({fieldType} {paramName})");
                sb.AppendLine("    {");
                sb.AppendLine($"        int keyValue = (int){paramName};");
                sb.AppendLine($"        if ((uint)keyValue >= (uint)_rangesBy{sk.Field.Name}.Length)");
                sb.AppendLine($"            return RangeView<{model.TypeName}>.Empty;");
                sb.AppendLine($"        var (start, count) = _rangesBy{sk.Field.Name}[keyValue];");
                sb.AppendLine("        return new RangeView<{0}>(_records.AsSpan(start, count));", model.TypeName);
                sb.AppendLine("    }");
                sb.AppendLine();
            }
        }

        // Range query by primary key
        if (model.PrimaryKey != null)
        {
            var pk = model.PrimaryKey;

            // Always generate int overload
            RenderFindRangeByPrimaryKey(sb, model, pk, "int");

            // Generate GameDataId overload
            RenderFindRangeByPrimaryKey(sb, model, pk, "GameDataId");

            // Generate enum overload if convention-based enum type exists
            var enumType = GetConventionalEnumType(model.TypeName);
            if (enumType != null)
            {
                RenderFindRangeByPrimaryKey(sb, model, pk, enumType);
            }

            // Helper methods for binary search
            sb.AppendLine("    private int LowerBound(int targetId)");
            sb.AppendLine("    {");
            sb.AppendLine("        int lo = 0, hi = _count;");
            sb.AppendLine("        while (lo < hi)");
            sb.AppendLine("        {");
            sb.AppendLine("            int mid = lo + ((hi - lo) >> 1);");
            sb.AppendLine("            if (GetPrimaryKey(_records[mid]) < targetId)");
            sb.AppendLine("                lo = mid + 1;");
            sb.AppendLine("            else");
            sb.AppendLine("                hi = mid;");
            sb.AppendLine("        }");
            sb.AppendLine("        return lo;");
            sb.AppendLine("    }");
            sb.AppendLine();

            sb.AppendLine("    private int UpperBound(int targetId)");
            sb.AppendLine("    {");
            sb.AppendLine("        int lo = 0, hi = _count;");
            sb.AppendLine("        while (lo < hi)");
            sb.AppendLine("        {");
            sb.AppendLine("            int mid = lo + ((hi - lo) >> 1);");
            sb.AppendLine("            if (GetPrimaryKey(_records[mid]) <= targetId)");
            sb.AppendLine("                lo = mid + 1;");
            sb.AppendLine("            else");
            sb.AppendLine("                hi = mid;");
            sb.AppendLine("        }");
            sb.AppendLine("        return lo;");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        // ThrowHelper
        sb.AppendLine("    private static void ThrowKeyNotFound(string keyName, int value)");
        sb.AppendLine("    {");
        sb.AppendLine($"        throw new KeyNotFoundException($\"{model.TypeName}.{{keyName}}={{value}} not found\");");
        sb.AppendLine("    }");

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void AppendLine(this StringBuilder sb, string format, params object[] args)
    {
        sb.AppendLine(string.Format(format, args));
    }

    private static string ToCamelCase(string name)
    {
        if (string.IsNullOrEmpty(name)) return name;
        return char.ToLowerInvariant(name[0]) + name.Substring(1);
    }

    /// <summary>
    /// Convention-based enum type detection.
    /// ZombieTypeData -> ZombieTypeId
    /// UnitTypeData -> UnitTypeId
    /// BuildingTypeData -> BuildingTypeId
    /// </summary>
    private static string? GetConventionalEnumType(string typeName)
    {
        if (typeName.EndsWith("Data"))
        {
            return typeName.Substring(0, typeName.Length - 4) + "Id";
        }
        return null;
    }

    private static void RenderFindByPrimaryKey(StringBuilder sb, TableSchemaModel model, FieldInfo pk, string paramType, string paramName)
    {
        sb.AppendLine($"    /// <summary>O(1) lookup by {pk.Name} using slot array.</summary>");
        sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"    public ref readonly {model.TypeName} FindBy{pk.Name}({paramType} {paramName})");
        sb.AppendLine("    {");
        sb.AppendLine($"        int keyValue = {GetKeyValueExpression(paramType, paramName)};");
        sb.AppendLine($"        if ((uint)keyValue > (uint)_maxPrimaryKey)");
        sb.AppendLine($"            ThrowKeyNotFound(\"{pk.Name}\", keyValue);");
        sb.AppendLine($"        int slot = _slotBy{pk.Name}[keyValue];");
        sb.AppendLine("        if (slot < 0)");
        sb.AppendLine($"            ThrowKeyNotFound(\"{pk.Name}\", keyValue);");
        sb.AppendLine("        return ref _records[slot];");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void RenderTryFindByPrimaryKey(StringBuilder sb, TableSchemaModel model, FieldInfo pk, string paramType, string paramName)
    {
        sb.AppendLine($"    /// <summary>O(1) lookup by {pk.Name}, returns false if not found.</summary>");
        sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"    public bool TryFindBy{pk.Name}({paramType} {paramName}, out {model.TypeName} result)");
        sb.AppendLine("    {");
        sb.AppendLine($"        int keyValue = {GetKeyValueExpression(paramType, paramName)};");
        sb.AppendLine($"        if ((uint)keyValue <= (uint)_maxPrimaryKey)");
        sb.AppendLine("        {");
        sb.AppendLine($"            int slot = _slotBy{pk.Name}[keyValue];");
        sb.AppendLine("            if (slot >= 0)");
        sb.AppendLine("            {");
        sb.AppendLine("                result = _records[slot];");
        sb.AppendLine("                return true;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("        result = default;");
        sb.AppendLine("        return false;");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static string GetKeyValueExpression(string paramType, string paramName)
    {
        if (paramType == "int")
            return paramName;
        if (paramType == "GameDataId")
            return $"{paramName}.Value";
        // Enum type - cast to int
        return $"(int){paramName}";
    }

    private static void RenderFindRangeByPrimaryKey(StringBuilder sb, TableSchemaModel model, FieldInfo pk, string paramType)
    {
        sb.AppendLine($"    /// <summary>Range query - returns all records with {pk.Name} in [min{pk.Name}, max{pk.Name}]. O(log n + k) via binary search.</summary>");
        sb.AppendLine($"    public RangeView<{model.TypeName}> FindRangeBy{pk.Name}({paramType} min{pk.Name}, {paramType} max{pk.Name})");
        sb.AppendLine("    {");
        sb.AppendLine($"        int lo = LowerBound({GetKeyValueExpression(paramType, $"min{pk.Name}")});");
        sb.AppendLine($"        int hi = UpperBound({GetKeyValueExpression(paramType, $"max{pk.Name}")});");
        sb.AppendLine("        if (lo >= hi) return RangeView<{0}>.Empty;", model.TypeName);
        sb.AppendLine("        return new RangeView<{0}>(_records.AsSpan(lo, hi - lo));", model.TypeName);
        sb.AppendLine("    }");
        sb.AppendLine();
    }
}
