namespace DieDrifterDie.GameApp.AppState;

/// <summary>
/// Immutable state representing the current lobby.
/// Use With* methods to create modified copies.
/// </summary>
public readonly record struct LobbyState
{
    /// <summary>Maximum number of players in a lobby.</summary>
    public const int MaxPlayers = 8;

    /// <summary>All connected clients in the lobby.</summary>
    public ConnectedClient[] Clients { get; init; }

    /// <summary>Session seed for deterministic random. Generated by coordinator, synced to all clients.</summary>
    public int SessionSeed { get; init; }

    /// <summary>Number of connected clients.</summary>
    public int PlayerCount => Clients.Length;

    /// <summary>Empty lobby state.</summary>
    public static readonly LobbyState Empty = new()
    {
        Clients = Array.Empty<ConnectedClient>(),
        SessionSeed = 0
    };

    /// <summary>
    /// Creates a new lobby with the local client as first player (coordinator).
    /// </summary>
    public static LobbyState CreateWithHost(LocalClient host)
    {
        var hostClient = new ConnectedClient(
            ClientId: host.ClientId,
            PlayerSlot: 0,
            DisplayName: host.DisplayName,
            IsReady: false,
            IsLoaded: false
        );

        return new LobbyState
        {
            Clients = new[] { hostClient }
        };
    }

    /// <summary>
    /// Gets the client in the specified slot (coordinator is typically slot 0).
    /// </summary>
    public ConnectedClient? GetClientBySlot(int slot)
    {
        for (int i = 0; i < Clients.Length; i++)
        {
            if (Clients[i].PlayerSlot == slot)
            {
                return Clients[i];
            }
        }
        return null;
    }

    /// <summary>
    /// Gets the next available player slot (0-7).
    /// Returns -1 if no slots available.
    /// </summary>
    public int GetNextAvailableSlot()
    {
        Span<bool> usedSlots = stackalloc bool[MaxPlayers];
        for (int i = 0; i < Clients.Length; i++)
        {
            int slot = Clients[i].PlayerSlot;
            if (slot >= 0 && slot < MaxPlayers)
            {
                usedSlots[slot] = true;
            }
        }

        for (int i = 0; i < MaxPlayers; i++)
        {
            if (!usedSlots[i])
            {
                return i;
            }
        }

        return -1;
    }

    /// <summary>
    /// Gets a client by their ClientId.
    /// </summary>
    public ConnectedClient? GetClient(Guid clientId)
    {
        for (int i = 0; i < Clients.Length; i++)
        {
            if (Clients[i].ClientId == clientId)
            {
                return Clients[i];
            }
        }
        return null;
    }

    /// <summary>
    /// Checks if all connected clients are ready.
    /// </summary>
    public bool AreAllClientsReady()
    {
        if (Clients.Length == 0)
        {
            return false;
        }

        for (int i = 0; i < Clients.Length; i++)
        {
            if (!Clients[i].IsReady)
            {
                return false;
            }
        }

        return true;
    }

    /// <summary>
    /// Checks if all connected clients have confirmed loaded.
    /// </summary>
    public bool AreAllClientsLoaded()
    {
        if (Clients.Length == 0)
        {
            return false;
        }

        for (int i = 0; i < Clients.Length; i++)
        {
            if (!Clients[i].IsLoaded)
            {
                return false;
            }
        }

        return true;
    }

    /// <summary>
    /// Gets the count of ready clients.
    /// </summary>
    public int GetReadyCount()
    {
        int count = 0;
        for (int i = 0; i < Clients.Length; i++)
        {
            if (Clients[i].IsReady)
            {
                count++;
            }
        }
        return count;
    }

    /// <summary>
    /// Gets the count of loaded clients.
    /// </summary>
    public int GetLoadedCount()
    {
        int count = 0;
        for (int i = 0; i < Clients.Length; i++)
        {
            if (Clients[i].IsLoaded)
            {
                count++;
            }
        }
        return count;
    }

    /// <summary>
    /// Returns a new LobbyState with the specified client's ready status updated.
    /// </summary>
    public LobbyState WithClientReady(Guid clientId, bool ready)
    {
        var newClients = new ConnectedClient[Clients.Length];
        for (int i = 0; i < Clients.Length; i++)
        {
            if (Clients[i].ClientId == clientId)
            {
                newClients[i] = Clients[i] with { IsReady = ready };
            }
            else
            {
                newClients[i] = Clients[i];
            }
        }
        return this with { Clients = newClients };
    }

    /// <summary>
    /// Returns a new LobbyState with the specified client's loaded status updated.
    /// </summary>
    public LobbyState WithClientLoaded(Guid clientId, bool loaded)
    {
        var newClients = new ConnectedClient[Clients.Length];
        for (int i = 0; i < Clients.Length; i++)
        {
            if (Clients[i].ClientId == clientId)
            {
                newClients[i] = Clients[i] with { IsLoaded = loaded };
            }
            else
            {
                newClients[i] = Clients[i];
            }
        }
        return this with { Clients = newClients };
    }

    /// <summary>
    /// Returns a new LobbyState with the specified client added.
    /// </summary>
    public LobbyState WithClientAdded(ConnectedClient client)
    {
        var newClients = new ConnectedClient[Clients.Length + 1];
        Array.Copy(Clients, newClients, Clients.Length);
        newClients[Clients.Length] = client;
        return this with { Clients = newClients };
    }

    /// <summary>
    /// Returns a new LobbyState with the specified client removed.
    /// </summary>
    public LobbyState WithClientRemoved(Guid clientId)
    {
        int indexToRemove = -1;
        for (int i = 0; i < Clients.Length; i++)
        {
            if (Clients[i].ClientId == clientId)
            {
                indexToRemove = i;
                break;
            }
        }

        if (indexToRemove < 0)
        {
            return this;
        }

        var newClients = new ConnectedClient[Clients.Length - 1];
        int destIndex = 0;
        for (int i = 0; i < Clients.Length; i++)
        {
            if (i != indexToRemove)
            {
                newClients[destIndex++] = Clients[i];
            }
        }

        return this with { Clients = newClients };
    }
}
