#nullable enable
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ConfigRefresh.Generator
{
    /// <summary>
    /// Generates a partial SimWorld class with BeginFrame overload
    /// that handles entity config refresh with generation tracking.
    /// </summary>
    internal static class SimWorldRefreshRenderer
    {
        public static string Render(IEnumerable<ConfigSourceModel> models)
        {
            var validModels = models.Where(m => m != null).ToList();
            if (validModels.Count == 0)
                return string.Empty;

            // Get namespace from first model (all should be in same namespace)
            var firstModel = validModels[0];
            var ns = firstModel.Type.ContainingNamespace?.ToDisplayString() ?? "global";
            // Get GameDocDb namespace from the data type's namespace
            var gameDocDbNs = firstModel.TableType.ContainingNamespace?.ToDisplayString() ?? "GameData.Schemas";
            var gameDocDbType = $"{gameDocDbNs}.GameDocDb";

            var sb = new StringBuilder(2048);
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
            sb.AppendLine("    partial class SimWorld");
            sb.AppendLine("    {");

            // HOT_RELOAD version with generation tracking
            sb.AppendLine("#if HOT_RELOAD");
            sb.AppendLine("        private int _entityConfigGeneration = -1;");
            sb.AppendLine();
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Performs spatial sorting and refreshes entity configs if generation changed.");
            sb.AppendLine("        /// Call this at the start of each simulation tick.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        public void BeginFrame(int generation, {gameDocDbType} db)");
            sb.AppendLine("        {");
            sb.AppendLine("            BeginFrame();  // Core spatial sorting");
            sb.AppendLine();
            sb.AppendLine("            if (_entityConfigGeneration == generation) return;");
            sb.AppendLine("            _entityConfigGeneration = generation;");
            sb.AppendLine();

            foreach (var model in validModels)
            {
                var tableName = model.Type.Name + "s"; // CombatUnitRow -> CombatUnitRows
                sb.AppendLine($"            {tableName}.RefreshStats(db);");
            }
            sb.AppendLine("            // Note: RecomputeAll runs next frame via BeginFrame()");

            sb.AppendLine("        }");

            // Production version - just calls BeginFrame
            sb.AppendLine("#else");
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Performs spatial sorting. Entity config refresh is disabled in production.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine($"        public void BeginFrame(int generation, {gameDocDbType} db) => BeginFrame();");
            sb.AppendLine("#endif");

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }
    }
}
