#nullable enable
using System.Text;

namespace ConfigRefresh.Generator
{
    internal static class SystemRefreshRenderer
    {
        public static string Render(ConfigSourceModel model)
        {
            var ns = model.Type.ContainingNamespace?.ToDisplayString() ?? "global";
            var typeName = model.Type.Name;
            var tablePropertyName = model.TableType.Name; // e.g., SeparationConfigData
            // Get GameDocDb namespace from the data type's namespace
            var gameDocDbNs = model.TableType.ContainingNamespace?.ToDisplayString() ?? "GameData.Schemas";
            var gameDocDbType = $"{gameDocDbNs}.GameDocDb";

            var sb = new StringBuilder(4096);
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
            sb.AppendLine($"    partial class {typeName}");
            sb.AppendLine("    {");

            // Private generation tracking field
            sb.AppendLine("#if HOT_RELOAD");
            sb.AppendLine("        private int _configGeneration = -1;");
            sb.AppendLine("#endif");
            sb.AppendLine();

            // RefreshConfigIfStale method
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Refreshes cached config values if the GameData generation has changed.");
            sb.AppendLine("        /// Call this at the start of Tick() for hot-reload support.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("#if HOT_RELOAD");
            sb.AppendLine($"        public void RefreshConfigIfStale(int generation, {gameDocDbType} db)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (_configGeneration == generation) return;");
            sb.AppendLine("            _configGeneration = generation;");
            sb.AppendLine();

            // Get config row
            sb.AppendLine($"            ref readonly var config = ref db.{tablePropertyName}.FindById({model.RowId});");
            sb.AppendLine();

            // Refresh each field
            foreach (var field in model.CachedFields)
            {
                sb.AppendLine($"            {field.FieldName} = config.{field.SourcePropertyName};");
            }

            sb.AppendLine();
            sb.AppendLine("            OnConfigRefreshed();");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Called after config values are refreshed. Implement this partial method");
            sb.AppendLine("        /// to update computed fields or reallocate buffers.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        partial void OnConfigRefreshed();");
            sb.AppendLine("#else");
            sb.AppendLine("        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine($"        public void RefreshConfigIfStale(int generation, {gameDocDbType} db) {{ }}");
            sb.AppendLine("#endif");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }
    }
}
