namespace BaseTemplate.Simulation.Components;

/// <summary>
/// SimWorld partial class for manual extensions.
/// Most methods are auto-generated by SimTable.Generator.
/// </summary>
public sealed partial class SimWorld
{
}
