using System.Text.Json;

namespace DerpTech.DesyncDetection;

/// <summary>
/// Interface for exporting simulation state to JSON for desync debugging.
/// Implemented by SimWorld (generated by SimTable.Generator).
/// </summary>
public interface IDesyncExportable
{
    /// <summary>
    /// Exports complete state to JSON for desync debugging.
    /// Includes all tables with all fields and their raw values.
    /// </summary>
    void ExportDebugJson(Utf8JsonWriter writer);
}
