using System;
using SimTable;

namespace Catrillion.Simulation.Components;

/// <summary>
/// Extension methods for BuildingRowRowRef providing span-based garrison access.
/// Uses GarrisonSlotArray span accessor generated by [Array(6)] attribute.
/// </summary>
public static class BuildingRowGarrisonExtensions
{
    /// <summary>
    /// Get garrison slot handle by index using span accessor.
    /// </summary>
    public static SimHandle GetGarrisonSlot(ref this BuildingRowRowRef building, int index)
    {
        var slots = building.GarrisonSlotArray;
        if (index < 0 || index >= slots.Length) return SimHandle.Invalid;
        return slots[index];
    }

    /// <summary>
    /// Find first empty slot index, or -1 if full.
    /// </summary>
    public static int FindEmptyGarrisonSlot(ref this BuildingRowRowRef building)
    {
        int capacity = Math.Min((int)building.GarrisonCapacity, 6);
        var slots = building.GarrisonSlotArray;

        for (int i = 0; i < capacity; i++)
        {
            if (!slots[i].IsValid) return i;
        }
        return -1;
    }

    /// <summary>
    /// Find slot containing the given unit, or -1 if not found.
    /// </summary>
    public static int FindUnitInGarrison(ref this BuildingRowRowRef building, SimHandle unitHandle)
    {
        int count = Math.Min((int)building.GarrisonCount, 6);
        var slots = building.GarrisonSlotArray;

        for (int i = 0; i < count; i++)
        {
            if (slots[i].Equals(unitHandle)) return i;
        }
        return -1;
    }

    /// <summary>
    /// Remove unit from garrison slot and compact remaining slots.
    /// </summary>
    public static void RemoveFromGarrison(ref this BuildingRowRowRef building, int slotIndex)
    {
        if (slotIndex < 0 || slotIndex >= 6) return;

        var slots = building.GarrisonSlotArray;

        // Shift remaining slots down to compact
        for (int i = slotIndex; i < slots.Length - 1; i++)
        {
            slots[i] = slots[i + 1];
        }
        slots[slots.Length - 1] = SimHandle.Invalid;

        if (building.GarrisonCount > 0)
            building.GarrisonCount--;
    }

    /// <summary>
    /// Add unit to first available garrison slot.
    /// Returns true if successfully added, false if no space.
    /// </summary>
    public static bool TryAddToGarrison(ref this BuildingRowRowRef building, SimHandle unitHandle)
    {
        if (building.GarrisonCount >= building.GarrisonCapacity) return false;

        var slots = building.GarrisonSlotArray;

        for (int i = 0; i < slots.Length; i++)
        {
            if (!slots[i].IsValid)
            {
                slots[i] = unitHandle;
                building.GarrisonCount++;
                return true;
            }
        }

        return false;
    }

    /// <summary>
    /// Check if building has space for more garrisoned units.
    /// </summary>
    public static bool HasGarrisonSpace(ref this BuildingRowRowRef building) =>
        building.GarrisonCount < building.GarrisonCapacity;
}
