using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace DerpTech2D.AotGen;

[Generator(LanguageNames.CSharp)]
public sealed class AotSchemaGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var compilationProvider = context.CompilationProvider;

        var candidateTypes = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is StructDeclarationSyntax || node is RecordDeclarationSyntax r && r.ClassOrStructKeyword.Kind() == SyntaxKind.StructKeyword,
                static (ctx, _) => ctx.SemanticModel.GetDeclaredSymbol(ctx.Node) as INamedTypeSymbol)
            .Where(static t => t is not null)!
            .Select((t, _) => t!);

        var inputs = candidateTypes.Collect().Combine(compilationProvider);

        context.RegisterSourceOutput(inputs, static (spc, tuple) =>
        {
            var (candidates, compilation) = tuple;
            var iComponent = compilation.GetTypeByMetadataName("Friflo.Engine.ECS.IComponent");
            if (iComponent is null)
            {
                // Friflo not referenced; nothing to generate
                return;
            }

            var components = new List<INamedTypeSymbol>();

            // Collect components from current compilation (source code)
            foreach (var type in candidates)
            {
                try
                {
                    if (type.TypeKind == TypeKind.Struct && Implements(type, iComponent))
                    {
                        components.Add(type);
                    }
                }
                catch
                {
                    // ignore malformed symbols
                }
            }

            // Also scan referenced assemblies for IComponent types
            foreach (var reference in compilation.References)
            {
                if (compilation.GetAssemblyOrModuleSymbol(reference) is IAssemblySymbol assembly)
                {
                    CollectComponentsFromAssembly(assembly.GlobalNamespace, iComponent, components);
                }
            }

            var source = GenerateSource(compilation.AssemblyName ?? "DerpTech2D", components);
            spc.AddSource("AotSchema.g.cs", source);
        });
    }

    private static bool Implements(INamedTypeSymbol type, INamedTypeSymbol iface)
    {
        foreach (var i in type.AllInterfaces)
        {
            if (SymbolEqualityComparer.Default.Equals(i, iface)) return true;
        }
        return false;
    }

    private static void CollectComponentsFromAssembly(
        INamespaceSymbol ns,
        INamedTypeSymbol iComponent,
        List<INamedTypeSymbol> components)
    {
        // Skip system/runtime assemblies to avoid scanning too much
        var nsName = ns.ToDisplayString();
        if (nsName.StartsWith("System", StringComparison.Ordinal) ||
            nsName.StartsWith("Microsoft", StringComparison.Ordinal) ||
            nsName.StartsWith("Friflo", StringComparison.Ordinal))
        {
            return;
        }

        foreach (var member in ns.GetMembers())
        {
            if (member is INamespaceSymbol childNs)
            {
                CollectComponentsFromAssembly(childNs, iComponent, components);
            }
            else if (member is INamedTypeSymbol type)
            {
                try
                {
                    if (type.TypeKind == TypeKind.Struct &&
                        type.DeclaredAccessibility == Accessibility.Public &&
                        Implements(type, iComponent))
                    {
                        // Avoid duplicates
                        if (!components.Any(c => SymbolEqualityComparer.Default.Equals(c, type)))
                        {
                            components.Add(type);
                        }
                    }
                }
                catch
                {
                    // ignore malformed symbols
                }
            }
        }
    }

    private static string GenerateSource(string assemblyName, IReadOnlyList<INamedTypeSymbol> components)
    {
        // Prefer project assembly name as namespace if it is a valid identifier; else fallback
        var ns = SanitizeNamespace(assemblyName);
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/> Generated by AotSchemaGenerator");
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine("public static partial class AotSchema");
        sb.AppendLine("{");
        sb.AppendLine("    public static void Create()");
        sb.AppendLine("    {");
        sb.AppendLine("        var aot = new global::Friflo.Engine.ECS.NativeAOT();");
        foreach (var comp in components.OrderBy(c => c.ToDisplayString()))
        {
            var name = comp.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            sb.Append("        aot.RegisterComponent<").Append(name).AppendLine(">();");
        }
        sb.AppendLine("        aot.CreateSchema();");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string SanitizeNamespace(string asm)
    {
        // Very simple: allow letters, digits, underscore, dot; replace others with underscore
        var chars = asm.Select(ch => char.IsLetterOrDigit(ch) || ch == '_' || ch == '.' ? ch : '_').ToArray();
        var ns = new string(chars);
        if (string.IsNullOrWhiteSpace(ns)) ns = "Generated";
        return ns;
    }
}

